import os
from dotenv import load_dotenv
from typing import Any

from langchain_core.chat_history import BaseChatMessageHistory
from langchain_community.chat_message_histories import ChatMessageHistory
from langchain_community.vectorstores import FAISS
from langchain_core.runnables.history import RunnableWithMessageHistory
from langchain.chains import create_history_aware_retriever
from langchain.chains.combine_documents import create_stuff_documents_chain

from utils.model_loader import ModelLoader
from exceptions.custom_exceptions import DocumentPortalException
from prompts.prompt_library import contextualize_question_prompt, context_qa_prompt


class ConversationalRAG:
    def __init__(self, session_id: str, retriever: Any):
        try:
            load_dotenv()  # Load environment variables
            self.session_id = session_id
            self.retriever = retriever
            self.llm = self._load_llm()

            self.contextualize_prompt = contextualize_question_prompt
            self.qa_prompt = context_qa_prompt

            self.history_aware_retriever = create_history_aware_retriever(
                self.llm, self.retriever, self.contextualize_prompt
            )

            self.qa_chain = create_stuff_documents_chain(
                llm=self.llm,
                prompt=self.qa_prompt
            )

            self.chain = RunnableWithMessageHistory(
                self.qa_chain,
                self._get_session_history,
                input_messages_key="input",        # Match prompt's expected input
                history_messages_key="chat_history",
                output_messages_key="answer"       # Match prompt's expected output
            )

            print(f"[INFO] ConversationalRAG initialized for session: {self.session_id}")

        except Exception as e:
            print(f"[ERROR] Error initializing ConversationalRAG: {e}")
            raise DocumentPortalException(
                "Error initializing ConversationalRAG",
                error_details=str(e)
            ) from e

    def _load_llm(self) -> Any:
        try:
            loader = ModelLoader()
            llm = loader.load_llm()
            print("[INFO] LLM model loaded successfully")
            return llm
        except Exception as e:
            print(f"[ERROR] Error loading LLM model: {e}")
            raise DocumentPortalException(
                "Error loading LLM model",
                error_details=str(e)
            ) from e

    def load_retriever_from_faiss(self, faiss_dir: str) -> Any:
        try:
            embedding_model = ModelLoader().load_embeddings()
            if not os.path.exists(faiss_dir):
                raise FileNotFoundError(f"FAISS directory not found: {faiss_dir}")

            vector_store = FAISS.load_local(faiss_dir, embedding_model)
            print(f"[INFO] FAISS vector store loaded from {faiss_dir}")
            return vector_store.as_retriever(search_type="similarity", search_kwargs={"k": 3})

        except Exception as e:
            print(f"[ERROR] Error loading FAISS retriever: {e}")
            raise DocumentPortalException(
                "Error loading FAISS retriever",
                error_details=str(e)
            ) from e

    def _get_session_history(self, session_id: str) -> BaseChatMessageHistory:
        return ChatMessageHistory(session_id=session_id)

    def invoke(self, question: str) -> str:
        try:
            response = self.chain.invoke(
                {"input": question},
                config={"configurable": {"session_id": self.session_id}}
            )
            answer = response.get("answer")
            if not answer:
                raise ValueError("No answer generated by the model.")
            print(f"[INFO] Response generated successfully for session: {self.session_id}")
            return answer
        except Exception as e:
            print(f"[ERROR] Error generating response: {e}")
            raise DocumentPortalException(
                "Error generating response",
                error_details=str(e)
            ) from e
